va_platform_home:
    path: /
    defaults: {_controller : VAPlatformBundle:Default:index}

va_platform_search:
    path: /research
    defaults: {_controller : VAPlatformBundle:Default:research}

va_platform_car:
    path: /car/{slugurl}
    defaults: {_controller : VAPlatformBundle:Default:car}

va_platform_faq:
    path: /faq
    defaults: {_controller : VAPlatformBundle:Default:faq}
    
va_platform_login:
    path: /login1
    defaults: {_controller : VAPlatformBundle:Default:login}

va_platform_blog:
    path: /blog
    defaults:  {_controller : VAPlatformBundle:Default:blog}
    
va_platform_wait:
    path: /wait
    defaults:  {_controller : VAPlatformBundle:Default:wait}

EndroidQrCodeBundle:
    resource:   "@EndroidQrCodeBundle/Controller/"
    type:       annotation
    prefix:     /qrcode
    

