ad_platform_home:
    path:     /admin/home
    defaults: { _controller: ADPlatformBundle:Cars:index }

ad_platform_mycars:
    path:     /admin/mycars
    defaults: { _controller: ADPlatformBundle:Cars:myCars }

ad_platform_myfavs:
    path:     /admin/myfavs
    defaults: { _controller: ADPlatformBundle:Cars:myFavs }

ad_platform_newcar:
    path:     /admin/newcar
    defaults: { _controller: ADPlatformBundle:Cars:newCar }

ad_platform_editcar:
    path:       /admin/editcar/{id}
    defaults:   {_controller: ADPlatformBundle:Cars:editCar}
    
ad_platform_editcaradmin:
    path:       /admin/editcaradmin/{id}
    defaults:   {_controller: ADPlatformBundle:Cars:editCarAdmin}
    
ad_platform_addfav:
    path:       /add-to-favorite/{id}
    defaults:    {_controller: ADPlatformBundle:Cars:addFav}
    
ad_plaform_delete:
    path:       /delete/{id}
    defaults:    {_controller: ADPlatformBundle:Cars:deleteCar}

ad_platform_listcar: 
    path:       /admin/listreport
    defaults:   {_controller: ADPlatformBundle:Cars:myReportList}
    
ad_platform_report:
    path:       /report/{id}
    defaults:   {_controller: ADPlatformBundle:Cars:report}


