<?php

namespace AD\PlatformBundle\Entity;

/**
 * CarsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMotCle($motcle)
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb
                ->where('c.name LIKE :motcle')
                ->setParameter('motcle', $motcle)
                ;
    
        return $qb
                ->getQuery()
                ->getResult()
                ;
    }
}
